/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WordcloudLazyImport = createFileRoute('/wordcloud')()
const BarplotLazyImport = createFileRoute('/barplot')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WordcloudLazyRoute = WordcloudLazyImport.update({
  path: '/wordcloud',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/wordcloud.lazy').then((d) => d.Route))

const BarplotLazyRoute = BarplotLazyImport.update({
  path: '/barplot',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/barplot.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/barplot': {
      id: '/barplot'
      path: '/barplot'
      fullPath: '/barplot'
      preLoaderRoute: typeof BarplotLazyImport
      parentRoute: typeof rootRoute
    }
    '/wordcloud': {
      id: '/wordcloud'
      path: '/wordcloud'
      fullPath: '/wordcloud'
      preLoaderRoute: typeof WordcloudLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/barplot': typeof BarplotLazyRoute
  '/wordcloud': typeof WordcloudLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/barplot': typeof BarplotLazyRoute
  '/wordcloud': typeof WordcloudLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/barplot': typeof BarplotLazyRoute
  '/wordcloud': typeof WordcloudLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/barplot' | '/wordcloud'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/barplot' | '/wordcloud'
  id: '__root__' | '/' | '/barplot' | '/wordcloud'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BarplotLazyRoute: typeof BarplotLazyRoute
  WordcloudLazyRoute: typeof WordcloudLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BarplotLazyRoute: BarplotLazyRoute,
  WordcloudLazyRoute: WordcloudLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/barplot",
        "/wordcloud"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/barplot": {
      "filePath": "barplot.lazy.tsx"
    },
    "/wordcloud": {
      "filePath": "wordcloud.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
