/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BarplotLazyImport = createFileRoute('/barplot')()
const AnimatedBackgroundLazyImport = createFileRoute('/animated-background')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const BarplotLazyRoute = BarplotLazyImport.update({
  path: '/barplot',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/barplot.lazy').then((d) => d.Route))

const AnimatedBackgroundLazyRoute = AnimatedBackgroundLazyImport.update({
  path: '/animated-background',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/animated-background.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/animated-background': {
      id: '/animated-background'
      path: '/animated-background'
      fullPath: '/animated-background'
      preLoaderRoute: typeof AnimatedBackgroundLazyImport
      parentRoute: typeof rootRoute
    }
    '/barplot': {
      id: '/barplot'
      path: '/barplot'
      fullPath: '/barplot'
      preLoaderRoute: typeof BarplotLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/animated-background': typeof AnimatedBackgroundLazyRoute
  '/barplot': typeof BarplotLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/animated-background': typeof AnimatedBackgroundLazyRoute
  '/barplot': typeof BarplotLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/animated-background': typeof AnimatedBackgroundLazyRoute
  '/barplot': typeof BarplotLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/animated-background' | '/barplot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/animated-background' | '/barplot'
  id: '__root__' | '/' | '/animated-background' | '/barplot'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AnimatedBackgroundLazyRoute: typeof AnimatedBackgroundLazyRoute
  BarplotLazyRoute: typeof BarplotLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AnimatedBackgroundLazyRoute: AnimatedBackgroundLazyRoute,
  BarplotLazyRoute: BarplotLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/animated-background",
        "/barplot"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/animated-background": {
      "filePath": "animated-background.lazy.tsx"
    },
    "/barplot": {
      "filePath": "barplot.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
